apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootadmin
spec:
  selector:
    matchLabels:
      app: springbootadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootadmin
    spec:
      containers:
      - name: springbootadmin
        image: steeltoeoss/spring-boot-admin
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: springbootadmin
spec:
  ports:
  - port: 9090
    targetPort: 8080
  selector:
    app: springbootadmin
  type: LoadBalancer