apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootadmin
spec:
  selector:
    matchLabels:
      app: springbootadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootadmin
    spec:
      containers:
      - name: springbootadmin
        image: steeltoe.azurecr.io/spring-boot-admin
        ports:
        - containerPort: 9099
        resources:
          limits:
            memory: 512Mi
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: springbootadmin
spec:
  ports:
  - port: 9099
    targetPort: 9099
  selector:
    app: springbootadmin
  type: LoadBalancer