apiVersion: apps/v1
kind: Deployment
metadata:
  name: steeltoe-management
spec:
  selector:
    matchLabels:
      app: steeltoe-management
  replicas: 1
  template:
    metadata:
      labels:
        app: steeltoe-management
    spec:
      containers:
      - name: steeltoe-management
        image: steeltoe-management:v1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: steeltoe-management
spec:
  ports:
  - port: 5000
    targetPort: 8080
  selector:
    app: steeltoe-management
  type: LoadBalancer