// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteeltoeAllActuators.Providers;

namespace SteeltoeAllActuators.Migrations
{
    [DbContext(typeof(EmployeeData))]
    [Migration("20210715143614_InitialModelCreate")]
    partial class InitialModelCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("SteeltoeAllActuators.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08d6ed22-94e5-8e9c-14d5-047ca1939d31"),
                            Company = "Skiles LLC",
                            FirstName = "Blaze",
                            LastName = "Pouros",
                            Title = "synthesize compelling e-business"
                        },
                        new
                        {
                            Id = new Guid("370bc82d-c2d2-52b9-123b-f70ce02e54b6"),
                            Company = "Cremin Inc",
                            FirstName = "Jordyn",
                            LastName = "Smith",
                            Title = "envisioneer strategic portals"
                        },
                        new
                        {
                            Id = new Guid("3821e3d1-e77d-3fa4-c84b-db1d8965bb52"),
                            Company = "Mertz, Nitzsche and Kozey",
                            FirstName = "Jerrod",
                            LastName = "Lowe",
                            Title = "deploy user-centric blockchains"
                        },
                        new
                        {
                            Id = new Guid("fb76f967-54a2-15e5-f466-eea081d42b97"),
                            Company = "Windler, Ledner and Wunsch",
                            FirstName = "Alia",
                            LastName = "Davis",
                            Title = "leverage innovative interfaces"
                        },
                        new
                        {
                            Id = new Guid("4cde8566-407a-3d92-3d16-ee2d4325f6f6"),
                            Company = "Schaden Group",
                            FirstName = "Annamarie",
                            LastName = "Wilderman",
                            Title = "morph cross-platform metrics"
                        },
                        new
                        {
                            Id = new Guid("bc4ce4cf-c390-813a-e165-3ccf06c87925"),
                            Company = "Lakin, Schuppe and Bernhard",
                            FirstName = "Immanuel",
                            LastName = "Schultz",
                            Title = "harness web-enabled e-commerce"
                        },
                        new
                        {
                            Id = new Guid("79982f5c-e3c8-a8cc-9f7d-96f4d6ac7adc"),
                            Company = "Mann, Gottlieb and King",
                            FirstName = "Arno",
                            LastName = "Nikolaus",
                            Title = "synthesize real-time applications"
                        },
                        new
                        {
                            Id = new Guid("1e564f70-6502-2d70-1d34-94a20819826f"),
                            Company = "Graham LLC",
                            FirstName = "Carmella",
                            LastName = "Davis",
                            Title = "strategize ubiquitous e-markets"
                        },
                        new
                        {
                            Id = new Guid("961ecfe2-7734-ef6d-7c9f-5794758a9d18"),
                            Company = "Schiller Inc",
                            FirstName = "Santiago",
                            LastName = "Schamberger",
                            Title = "transition rich portals"
                        },
                        new
                        {
                            Id = new Guid("8801795b-38f4-e9a9-998c-3b3246d9f8a6"),
                            Company = "Terry, Goyette and Nitzsche",
                            FirstName = "Noel",
                            LastName = "Bogan",
                            Title = "redefine 24/365 infomediaries"
                        },
                        new
                        {
                            Id = new Guid("ce69bd33-e33d-6aa8-ec3a-bb76e5fb44f6"),
                            Company = "Zulauf, Dicki and Hegmann",
                            FirstName = "Ashton",
                            LastName = "Hirthe",
                            Title = "embrace user-centric e-commerce"
                        },
                        new
                        {
                            Id = new Guid("fc1441b2-6d71-657f-bec1-7a3f1b5ca993"),
                            Company = "Senger, Hauck and Parker",
                            FirstName = "Kelton",
                            LastName = "Pouros",
                            Title = "brand back-end networks"
                        },
                        new
                        {
                            Id = new Guid("4c11f253-615e-9c71-bc8b-a1946e7acc3b"),
                            Company = "Hodkiewicz - Schimmel",
                            FirstName = "Jasmin",
                            LastName = "Kunze",
                            Title = "brand granular action-items"
                        },
                        new
                        {
                            Id = new Guid("ad76a3bb-e190-99d0-3289-1d7b6e19605f"),
                            Company = "Wintheiser, Waelchi and Schoen",
                            FirstName = "Kelly",
                            LastName = "Feest",
                            Title = "matrix cross-media web services"
                        },
                        new
                        {
                            Id = new Guid("6ebb1f02-bc18-5200-d190-baebc40bdbba"),
                            Company = "Brown Inc",
                            FirstName = "Adrien",
                            LastName = "Shanahan",
                            Title = "maximize intuitive technologies"
                        },
                        new
                        {
                            Id = new Guid("f313bfdb-37ce-4abc-96db-8dc1152b1acd"),
                            Company = "Quigley, Feeney and Gottlieb",
                            FirstName = "Candelario",
                            LastName = "Ryan",
                            Title = "mesh 24/7 architectures"
                        },
                        new
                        {
                            Id = new Guid("739cff16-8082-2835-f492-58a80d849ad3"),
                            Company = "Labadie, Zboncak and Mayer",
                            FirstName = "Cecelia",
                            LastName = "Cummings",
                            Title = "target dynamic paradigms"
                        },
                        new
                        {
                            Id = new Guid("6e2f283f-6621-7c7a-6fb8-371fd7145a57"),
                            Company = "Bruen - Schoen",
                            FirstName = "Maxine",
                            LastName = "Homenick",
                            Title = "cultivate e-business technologies"
                        },
                        new
                        {
                            Id = new Guid("5c2035b5-6918-2370-555b-425806bad32c"),
                            Company = "Kohler Group",
                            FirstName = "Arden",
                            LastName = "Corkery",
                            Title = "whiteboard revolutionary networks"
                        },
                        new
                        {
                            Id = new Guid("8581268e-8543-30f3-842d-b9ec461d6306"),
                            Company = "Leuschke - Rippin",
                            FirstName = "Jaydon",
                            LastName = "Bosco",
                            Title = "leverage dynamic content"
                        },
                        new
                        {
                            Id = new Guid("f8e46c4c-d772-019f-9be0-cef1e8ebdfd0"),
                            Company = "Schowalter Group",
                            FirstName = "Elenor",
                            LastName = "Miller",
                            Title = "syndicate sexy models"
                        },
                        new
                        {
                            Id = new Guid("4e8496c8-1de9-8b6e-d5a2-38d7a1fabdac"),
                            Company = "Herman LLC",
                            FirstName = "Rubye",
                            LastName = "Ankunding",
                            Title = "extend innovative web-readiness"
                        },
                        new
                        {
                            Id = new Guid("bf13fa34-782e-65dd-8623-30db5250187e"),
                            Company = "Jast Inc",
                            FirstName = "Delbert",
                            LastName = "Schinner",
                            Title = "redefine scalable models"
                        },
                        new
                        {
                            Id = new Guid("484a2755-7f97-5672-7828-1aef0aae5d5d"),
                            Company = "Toy - Lang",
                            FirstName = "Emelie",
                            LastName = "Cummings",
                            Title = "maximize integrated initiatives"
                        },
                        new
                        {
                            Id = new Guid("0bf4d19f-d855-2ca9-caa5-69062d94cd07"),
                            Company = "Sanford and Sons",
                            FirstName = "Dino",
                            LastName = "Haley",
                            Title = "generate leading-edge e-services"
                        },
                        new
                        {
                            Id = new Guid("df80bfe4-b1b7-73a3-cd0d-a8c58b6601a0"),
                            Company = "Russel Inc",
                            FirstName = "Uriel",
                            LastName = "Mertz",
                            Title = "mesh killer systems"
                        },
                        new
                        {
                            Id = new Guid("f1cc4805-2f7e-7706-5d30-269658c97519"),
                            Company = "Schuppe - Rippin",
                            FirstName = "Evelyn",
                            LastName = "Gulgowski",
                            Title = "aggregate turn-key web-readiness"
                        },
                        new
                        {
                            Id = new Guid("48a9c2d8-0f04-8d7e-8f4f-da6ee4b2f59d"),
                            Company = "Goyette and Sons",
                            FirstName = "Austen",
                            LastName = "Stracke",
                            Title = "visualize killer networks"
                        },
                        new
                        {
                            Id = new Guid("4e620a78-0f1f-fd44-cc81-19bb86bd724e"),
                            Company = "Crooks, Marvin and Williamson",
                            FirstName = "Jamir",
                            LastName = "Olson",
                            Title = "enable virtual ROI"
                        },
                        new
                        {
                            Id = new Guid("a0b9189a-0b22-7b6d-f3d0-f9ac2f6e800a"),
                            Company = "Windler, Kihn and Purdy",
                            FirstName = "Joelle",
                            LastName = "Batz",
                            Title = "morph frictionless metrics"
                        },
                        new
                        {
                            Id = new Guid("3e63a5a7-71c8-12d5-4d84-f68b5ca975ab"),
                            Company = "Maggio and Sons",
                            FirstName = "Alice",
                            LastName = "Connelly",
                            Title = "exploit best-of-breed e-commerce"
                        },
                        new
                        {
                            Id = new Guid("d26411fe-c7b7-cf82-fa86-7a66093d2a5f"),
                            Company = "Shanahan Inc",
                            FirstName = "Julio",
                            LastName = "Sipes",
                            Title = "deliver efficient markets"
                        },
                        new
                        {
                            Id = new Guid("84f9eded-465c-2478-7add-3fb70c035a85"),
                            Company = "Ondricka - Jaskolski",
                            FirstName = "Jessica",
                            LastName = "Kerluke",
                            Title = "innovate proactive deliverables"
                        },
                        new
                        {
                            Id = new Guid("06548d68-41a0-7ffd-906c-e5c9cefe73b3"),
                            Company = "Deckow, Nolan and Nolan",
                            FirstName = "Naomie",
                            LastName = "Metz",
                            Title = "transition 24/7 infrastructures"
                        },
                        new
                        {
                            Id = new Guid("ef61e85c-c8a9-4bdd-f61c-cef2728438df"),
                            Company = "Green - Reilly",
                            FirstName = "Laurence",
                            LastName = "Olson",
                            Title = "enhance innovative web-readiness"
                        },
                        new
                        {
                            Id = new Guid("23d9c8dc-0575-3bf4-32c6-44599b90e6a4"),
                            Company = "Conn, Hackett and Bayer",
                            FirstName = "Lacey",
                            LastName = "Nolan",
                            Title = "visualize viral e-services"
                        },
                        new
                        {
                            Id = new Guid("b34c3d4c-af02-e5a5-ad12-e0eeb9d5f127"),
                            Company = "Batz, Hessel and Hoeger",
                            FirstName = "Adele",
                            LastName = "Walter",
                            Title = "engage robust technologies"
                        },
                        new
                        {
                            Id = new Guid("20df1216-1b0e-082d-7029-c8a7872f169e"),
                            Company = "Mohr - Greenfelder",
                            FirstName = "Anna",
                            LastName = "Schmitt",
                            Title = "productize e-business initiatives"
                        },
                        new
                        {
                            Id = new Guid("ef0112ba-d391-0c07-0cb7-ec9dc5c49ff6"),
                            Company = "Simonis LLC",
                            FirstName = "Nickolas",
                            LastName = "Jerde",
                            Title = "engineer 24/7 markets"
                        },
                        new
                        {
                            Id = new Guid("566ba194-3ab2-c846-68f9-66fc1a3d779c"),
                            Company = "Thompson, Mosciski and Nolan",
                            FirstName = "Paolo",
                            LastName = "McClure",
                            Title = "leverage user-centric users"
                        },
                        new
                        {
                            Id = new Guid("04ce5186-bcfd-073a-715b-f068b159d271"),
                            Company = "Schneider - Morar",
                            FirstName = "Jeremy",
                            LastName = "Jerde",
                            Title = "orchestrate back-end solutions"
                        },
                        new
                        {
                            Id = new Guid("e56d8aac-4c3b-c71b-bb07-2be877c36b3c"),
                            Company = "Willms - Ward",
                            FirstName = "Laurine",
                            LastName = "Hickle",
                            Title = "exploit sexy paradigms"
                        },
                        new
                        {
                            Id = new Guid("45205ec8-520c-aaac-db5f-58734e55cb24"),
                            Company = "Koelpin LLC",
                            FirstName = "Christa",
                            LastName = "Goldner",
                            Title = "generate real-time architectures"
                        },
                        new
                        {
                            Id = new Guid("ad328fc8-9432-78e8-190b-1cdd2cd5bb69"),
                            Company = "Nader Group",
                            FirstName = "Margaret",
                            LastName = "Dach",
                            Title = "incentivize proactive networks"
                        },
                        new
                        {
                            Id = new Guid("5ea18429-c786-de34-63c0-7c7d1ffe7846"),
                            Company = "Runolfsdottir, Bruen and Koelpin",
                            FirstName = "Destinee",
                            LastName = "Hettinger",
                            Title = "morph frictionless markets"
                        },
                        new
                        {
                            Id = new Guid("dcac4d43-f3e2-a1d0-5c83-adf289f252d7"),
                            Company = "Kuhic, Cormier and Kunde",
                            FirstName = "Catalina",
                            LastName = "Prosacco",
                            Title = "drive vertical convergence"
                        },
                        new
                        {
                            Id = new Guid("ab9e8ca0-3b9c-378c-f142-79880180ccab"),
                            Company = "Heidenreich Group",
                            FirstName = "Golda",
                            LastName = "Koss",
                            Title = "incubate sticky e-tailers"
                        },
                        new
                        {
                            Id = new Guid("8c74fa6b-2e10-f1fa-a316-426732f6bf48"),
                            Company = "Johnston Inc",
                            FirstName = "Chauncey",
                            LastName = "Harvey",
                            Title = "envisioneer 24/7 paradigms"
                        },
                        new
                        {
                            Id = new Guid("8662ad9e-3ee1-b272-9f97-3fa1c60026c2"),
                            Company = "Stroman, Braun and McCullough",
                            FirstName = "Flavio",
                            LastName = "Friesen",
                            Title = "expedite vertical schemas"
                        },
                        new
                        {
                            Id = new Guid("5598a932-2e3d-be1c-7bed-63cc740f64a3"),
                            Company = "Johnston, Walter and Wolff",
                            FirstName = "Mortimer",
                            LastName = "Bartell",
                            Title = "transform bricks-and-clicks vortals"
                        },
                        new
                        {
                            Id = new Guid("506a5067-39ba-7d34-82ae-95d95d616923"),
                            Company = "Kub - Kozey",
                            FirstName = "Ambrose",
                            LastName = "Robel",
                            Title = "recontextualize synergistic markets"
                        },
                        new
                        {
                            Id = new Guid("de9dae48-e52e-88b0-0380-d6ddb16ec0b4"),
                            Company = "Walsh Inc",
                            FirstName = "Anissa",
                            LastName = "Koch",
                            Title = "expedite 24/365 interfaces"
                        },
                        new
                        {
                            Id = new Guid("373a9231-d10e-93de-d8ea-080c9b554f9c"),
                            Company = "Heathcote, Rodriguez and Bahringer",
                            FirstName = "May",
                            LastName = "Kohler",
                            Title = "deploy synergistic synergies"
                        },
                        new
                        {
                            Id = new Guid("e1a8945e-b017-7b7e-36ac-9caa797932a1"),
                            Company = "Haag, Corwin and Murazik",
                            FirstName = "Mack",
                            LastName = "Spinka",
                            Title = "repurpose virtual mindshare"
                        },
                        new
                        {
                            Id = new Guid("55f3c163-a5db-c620-adb0-3c36b1c03989"),
                            Company = "Abshire - Jenkins",
                            FirstName = "Laverne",
                            LastName = "Roob",
                            Title = "integrate leading-edge solutions"
                        },
                        new
                        {
                            Id = new Guid("ab87473c-d50e-ba45-a88c-b4ef8b265b07"),
                            Company = "Osinski - Stiedemann",
                            FirstName = "Alaina",
                            LastName = "Schulist",
                            Title = "integrate web-enabled niches"
                        },
                        new
                        {
                            Id = new Guid("b323dc8d-4c31-df64-2d50-18941e74b7d7"),
                            Company = "Batz Group",
                            FirstName = "Dominique",
                            LastName = "Carroll",
                            Title = "incentivize granular bandwidth"
                        },
                        new
                        {
                            Id = new Guid("0c36a109-cbb7-d2ad-b442-1d31b291895c"),
                            Company = "Murazik, Farrell and Kihn",
                            FirstName = "Rigoberto",
                            LastName = "Howe",
                            Title = "target 24/365 paradigms"
                        },
                        new
                        {
                            Id = new Guid("db735df5-386d-de43-b9aa-8f15572762a2"),
                            Company = "Nienow, Haley and Block",
                            FirstName = "Hassan",
                            LastName = "Botsford",
                            Title = "scale open-source synergies"
                        },
                        new
                        {
                            Id = new Guid("c38836fd-435b-2fb8-dfc2-6e39f6470ada"),
                            Company = "Ledner Group",
                            FirstName = "Philip",
                            LastName = "Jakubowski",
                            Title = "transform wireless e-markets"
                        },
                        new
                        {
                            Id = new Guid("0ce6c797-a6b0-83cf-7ba9-7002ba1a5e67"),
                            Company = "Barrows Inc",
                            FirstName = "Anissa",
                            LastName = "Russel",
                            Title = "morph next-generation e-business"
                        },
                        new
                        {
                            Id = new Guid("2c337bd1-fff2-2deb-8828-2c935cac7e38"),
                            Company = "Stoltenberg - Zemlak",
                            FirstName = "Kristopher",
                            LastName = "Hirthe",
                            Title = "empower strategic metrics"
                        },
                        new
                        {
                            Id = new Guid("61228099-4857-2e6b-774d-3b3473a3917b"),
                            Company = "Pagac Group",
                            FirstName = "Makenna",
                            LastName = "Carter",
                            Title = "generate virtual e-business"
                        },
                        new
                        {
                            Id = new Guid("09723f66-02aa-c9c1-5bfb-9272dc89d53f"),
                            Company = "Harber - Aufderhar",
                            FirstName = "Hope",
                            LastName = "Nader",
                            Title = "cultivate front-end solutions"
                        },
                        new
                        {
                            Id = new Guid("938e4259-8e8e-cf48-75f7-fa18d6618374"),
                            Company = "Lynch LLC",
                            FirstName = "Kiana",
                            LastName = "Waters",
                            Title = "engineer one-to-one schemas"
                        },
                        new
                        {
                            Id = new Guid("f1d4396d-fbaf-1db9-7923-b067742e3acd"),
                            Company = "Carter - Murazik",
                            FirstName = "Natasha",
                            LastName = "Oberbrunner",
                            Title = "maximize distributed e-commerce"
                        },
                        new
                        {
                            Id = new Guid("ff83a679-4e70-3a3e-a359-2555ba571f7a"),
                            Company = "Dach, Hansen and Shields",
                            FirstName = "Meagan",
                            LastName = "Fisher",
                            Title = "aggregate real-time models"
                        },
                        new
                        {
                            Id = new Guid("224cc40c-a5ba-cfb1-7877-0877baac2be4"),
                            Company = "Brekke - Murray",
                            FirstName = "Bert",
                            LastName = "Kautzer",
                            Title = "cultivate leading-edge users"
                        },
                        new
                        {
                            Id = new Guid("1db2a781-aab6-a65e-26c7-6489f118e9b4"),
                            Company = "Farrell - Hartmann",
                            FirstName = "Katlyn",
                            LastName = "Schulist",
                            Title = "grow plug-and-play functionalities"
                        },
                        new
                        {
                            Id = new Guid("573bce72-55e4-f953-69a9-a012f29319ce"),
                            Company = "Homenick Group",
                            FirstName = "Flo",
                            LastName = "Casper",
                            Title = "maximize seamless functionalities"
                        },
                        new
                        {
                            Id = new Guid("5e9367db-7ad1-7e8c-2481-aae76f06c1d0"),
                            Company = "Orn - Towne",
                            FirstName = "Estevan",
                            LastName = "Kertzmann",
                            Title = "innovate web-enabled paradigms"
                        },
                        new
                        {
                            Id = new Guid("b5c6736c-8fb2-d0e9-dcdd-7c7dc1f427ee"),
                            Company = "Green LLC",
                            FirstName = "Molly",
                            LastName = "Veum",
                            Title = "visualize B2C models"
                        },
                        new
                        {
                            Id = new Guid("dc7f80a0-a983-04e6-a5b2-f25eb4d7cb94"),
                            Company = "Roob - Glover",
                            FirstName = "Euna",
                            LastName = "Maggio",
                            Title = "exploit user-centric partnerships"
                        },
                        new
                        {
                            Id = new Guid("552b3043-50e8-3af8-13b4-1432100c4d32"),
                            Company = "Hodkiewicz Group",
                            FirstName = "Eddie",
                            LastName = "Bins",
                            Title = "unleash transparent convergence"
                        },
                        new
                        {
                            Id = new Guid("0ed85955-cd26-5c88-71fe-98527d901b55"),
                            Company = "Sporer LLC",
                            FirstName = "Amely",
                            LastName = "Mraz",
                            Title = "transition magnetic convergence"
                        },
                        new
                        {
                            Id = new Guid("129ad98d-ff6b-797e-f5e6-008f77ea1446"),
                            Company = "Little, Carter and Schmeler",
                            FirstName = "Mohammed",
                            LastName = "Zieme",
                            Title = "reinvent 24/7 e-tailers"
                        },
                        new
                        {
                            Id = new Guid("7f4a5582-823a-d4bc-4d80-4c3376f07180"),
                            Company = "Ziemann - Langworth",
                            FirstName = "Rudy",
                            LastName = "McLaughlin",
                            Title = "architect extensible synergies"
                        },
                        new
                        {
                            Id = new Guid("d90ad403-1772-2592-33b5-e9aa33faba63"),
                            Company = "Reilly, Schiller and Hamill",
                            FirstName = "Yasmine",
                            LastName = "Koch",
                            Title = "target scalable users"
                        },
                        new
                        {
                            Id = new Guid("1c9e5590-cfd7-85a4-a77b-6678e26136ee"),
                            Company = "Reilly - Rowe",
                            FirstName = "Marcelino",
                            LastName = "Stamm",
                            Title = "drive seamless mindshare"
                        },
                        new
                        {
                            Id = new Guid("b4d24c34-db65-1ef0-438a-e2c2f4085be6"),
                            Company = "Hilll, Bailey and Bayer",
                            FirstName = "Oswald",
                            LastName = "Koss",
                            Title = "transform real-time deliverables"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
