// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Steeltoe.Samples.ActuatorApi.Data;

#nullable disable

namespace Steeltoe.Samples.ActuatorApi.Migrations;

[DbContext(typeof(WeatherDbContext))]
partial class WeatherContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Steeltoe.Samples.ActuatorApi.Models.WeatherForecast", b =>
            {
                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<string>("Summary")
                    .HasColumnType("longtext");

                b.Property<int>("TemperatureC")
                    .HasColumnType("int");

                b.HasKey("Date");

                b.ToTable("Forecasts");
            });
#pragma warning restore 612, 618
    }
}
