AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging:
  LogLevel:
    Default: Information
    System: Warning
    Microsoft: Warning
    Steeltoe: Information
eureka:
  instance:
    StatusPageUrlPath: /actuator/info
    HealthCheckUrlPath: /actuator/health
mysql:
  client:
    username: root
    password: steeltoe
management:
  endpoints:
    actuator:
      exposure:
        include: [ "*" ]
  tracing:
    alwaysSample: true
    useShortTraceIds: true
    exporterEndpoint: http://zipkinserver:9411/api/v2/spans
---
spring:
  profiles: Docker
eureka:
  client:
    serviceUrl: http://eurekaserver:8761/eureka/
mysql:
  client:
    server: mysql
management:
  tracing:
    exporter:
      zipkin:
        endpoint: http://zipkinserver:9411/api/v2/spans
redis:
  client:
    host: redis
