eureka:
  client:
    shouldRegisterWithEureka: true
mysql:
  client:
    database: MusicStore
DefaultAdminUsername: Administrator@test.com
DefaultAdminPassword: YouShouldChangeThisPassword1!
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
