trigger:
  branches:
    include:
      - master
      - 2.x
  paths:
    include:
      - ci/*
      - environment.py
      - pylib/*
      - Security/src/AspDotNetCore/CloudFoundrySingleSignon/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: ../../../../ci/templates/cloud-foundry-uaac-job.yml
    parameters:
      feature: Security
      sample: CloudFoundrySingleSignon
