parameters:
  feature: ''
  sample: ''
  behave_args: '--stop'
jobs:
- job: ${{parameters.feature}}_${{parameters.sample}}_Linux
  displayName: '${{parameters.feature}}: ${{parameters.sample}} (Linux)'
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-latest
  steps:
  - bash: echo Hello
    displayName: 'Display Hello'
