steps:
- bash: |
    cat >> user.ini << EOF
    [behave.userdata]
    cleanup = yes
    cmd_max_attempts = $STEELTOE_CMD_MAX_ATTEMPTS
    cmd_loop_wait = $STEELTOE_CMD_LOOP_WAIT
    cf_apiurl = $STEELTOE_CF_APIURL
    cf_org = $STEELTOE_CF_ORG
    cf_username = $STEELTOE_CF_USERNAME
    cf_password = $STEELTOE_CF_PASSWORD
    cf_max_attempts = $STEELTOE_CF_MAX_ATTEMPTS
    EOF
    cat user.ini
  env:
    STEELTOE_CF_USERNAME: $(STEELTOE_CF_USERNAME)
    STEELTOE_CF_PASSWORD: $(STEELTOE_CF_PASSWORD)
  displayName: 'Configure Behave'
