global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'ActuatorWeb'
    basic_auth:
      username: actuatorUser
      password: actuatorPassword
    static_configs:
      - targets: ['host.docker.internal:8090']
    metrics_path: /actuator/prometheus
    # The configuration below skips certificate validation
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true
  - job_name: 'ActuatorApi'
    basic_auth:
      username: actuatorUser
      password: actuatorPassword
    static_configs:
      - targets: ['host.docker.internal:8091']
    metrics_path: /actuator/prometheus
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true