trigger:
  branches:
    include:
    - main
    - pr-build-changed
  paths:
    exclude:
    - '*'
    - '**/*'
    include:
    - Management/src/ActuatorApi

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Management
      sample: ActuatorApi
