pr:
  paths:
    include:
    - Management/src/ActuatorApi
    exclude:
    - '*'
    - '/*'
    - '**/'
    - '**/*'

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Management
      sample: ActuatorApi
