trigger:
  branches:
    include:
      - main
      - latest
  paths:
    include:
      - config/*
      - Management/src/CloudFoundry/*

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Management
      sample: CloudFoundry
