trigger:
  branches:
    include:
    - main
    - pr-build-changed
  paths:
    include:
    - ci/templates
    - Connectors/src/PostgreSqlEFCore
    - Connectors/src/*.sln*

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: PostgreSqlEFCore
