pr:
  paths:
    include:
    - Connectors/src/PostgreSql

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: PostgreSql
