trigger:
  branches:
    include:
      - main
  paths:
    include:
      - config/*
      - Connectors/src/CosmosDb/*

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: CosmosDb
