trigger:
  branches:
    include:
    - main
    - 4.x
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-networkfileshares.yaml
    - FileShares/src/FileSharesWeb
pr:
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-networkfileshares.yaml
    - FileShares/src/FileSharesWeb

variables:
  - group: 'PCFone Credentials'
jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: FileShares
      sample: FileSharesWeb
      custom_variable: '''{"location":"$(FILESHARE_LOCATION)","username":"$(FILESHARE_USERNAME)","password":"$(FILESHARE_PASSWORD)"}'''
