trigger:
  branches:
    include:
    - main
    - pr-build-changed
  paths:
    include:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - ci/templates
    - Management/src/ActuatorApi
    - Management/src/*.sln*

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Management
      sample: ActuatorApi
