trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - Security/src/RedisDataProtection
pr:
  paths:
    exclude:
    - /*
    include:
    - Security/src/RedisDataProtection

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Security
      sample: RedisDataProtection
