trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-connectors-rabbitmq.yaml
    - Connectors/src/RabbitMQ
pr:
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-connectors-rabbitmq.yaml
    - Connectors/src/RabbitMQ

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: RabbitMQ
