trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-configuration.yaml
    - Configuration/src/ConfigurationProviders
pr:
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-configuration.yaml
    - Configuration/src/ConfigurationProviders

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Configuration
      sample: ConfigurationProviders
