trigger:
  branches:
    include:
    - main
    - pr-build-changed
  paths:
    include:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - ci/templates
    - Configuration
    - Configuration/src/*.sln*

variables:
  - group: 'PCFone Credentials'

jobs:
- job: Configuration_All_Linux
  displayName: 'Configuration: All (Linux)'
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-latest
  workspace:
    clean: all
  steps:
  - template: templates/setup-cloud-foundry-linux-steps.yaml
  - bash: touch reinit
    displayName: 'Reinit Virtual Python Environment'
  - bash: ./behave.sh Configuration/src/ConfigurationProviders '--stop'
    displayName: 'Sample -> Configuration: All'
    env:
      PYTHON: python3.10
  - template: templates/publish-results-steps.yaml
    parameters:
      feature: ConfigurationProviders
      sample: All
      os: Linux
