pr:
  paths:
    include:
    - Connectors/src/MySql
    exclude:
    - '*'
    - '**/'
    - '**/*'

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: MySql
