trigger:
  branches:
    include:
      - main
      - latest
  paths:
    include:
      - config/*
      - Security/src/RedisDataProtection/*

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Security
      sample: RedisDataProtection
