trigger: none
pr:
  paths:
    include:
    - Connectors/src/Redis
    exclude:
    - '/*'

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: Redis
