trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-management-cloudfoundry.yaml
    - Management/src/ActuatorApi
pr:
  paths:
    exclude:
    - /*
    include:
    - .gitattributes
    - .gitignore
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates
    - ci/azure-pipeline-management-cloudfoundry.yaml
    - Management/src/ActuatorApi

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Management
      sample: ActuatorApi
