trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - Connectors/src/CosmosDb
pr:
  paths:
    exclude:
    - /*
    include:
    - Connectors/src/CosmosDb

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: CosmosDb
