trigger:
  branches:
    include:
    - main
    - latest
    - pr-build-changed
  paths:
    include:
    - '**/*.py'
    - '**/*.sh'
    - '**/*.ini'
    - '**/*.ps1'
    - .editorconfig
    - .gitattributes
    - .gitignore
    - ci/templates
    - Connectors/src/PostgreSqlEFCore
    - Connectors/src/*.sln*
    exclude:
    - '**/*'

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: PostgreSqlEFCore
