trigger:
  branches:
    include:
    - main
    - latest
    - pr-build-changed
  paths:
    exclude:
    - '*'
    - '**/*'
    include:
    - Connectors/src/Redis

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: Redis
