trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /*
    include:
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates/*.yaml
    - ci/azure-pipeline-security-redis-data-protection.yaml
    - Security/src/RedisDataProtection
pr:
  paths:
    exclude:
    - /*
    include:
    - behave*
    - Pipfile*
    - pyenv.pkgs
    - '**/*.py'
    - ci/templates/*.yaml
    - ci/azure-pipeline-security-redis-data-protection.yaml
    - Security/src/RedisDataProtection

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Security
      sample: RedisDataProtection
