trigger:
  branches:
    include:
      - main
      - latest
  paths:
    include:
      - config/*
      - Configuration/src/Steeltoe.Samples.Configuration/*

variables:
  - group: 'PCFone Credentials'

jobs:
- job: Configuration_All_Linux
  displayName: 'Configuration: All (Linux)'
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-latest
  workspace:
    clean: all
  steps:
  - template: templates/setup-cloud-foundry-linux-steps.yaml
  - bash: touch reinit
    displayName: 'Reinit Virtual Python Environment'
  - bash: ./behave.sh Configuration/src/Steeltoe.Samples.Configuration '--stop'
    displayName: 'Sample -> Configuration: All'
    env:
      PYTHON: python3.10
  - template: templates/publish-results-steps.yaml
    parameters:
      feature: Configuration
      sample: All
      os: Linux