trigger:
  branches:
    include:
      - main
      - latest
  paths:
    include:
      - config/*
      - Configuration/src/Steeltoe.Samples.Configuration/*

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Configuration
      sample: Steeltoe.Samples.Configuration
