kind: Pod
apiVersion: v1
metadata:
  name: usage-sender
  labels:
    app: usage-cost-stream
spec:
  containers:
    - name: usage-sender
      image: hananiel/usagesender:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: SPRING_RABBITMQ_ADDRESSES
          value: rabbitmq
        - name: SERVER_PORT
          value: '8080'
  restartPolicy: Always

---
kind: Pod
apiVersion: v1
metadata:
  name: usage-processor
  labels:
    app: usage-cost-stream
spec:
  containers:
    - name: usage-processor
      image: hananiel/usageprocessor:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: SPRING_RABBITMQ_ADDRESSES
          value: rabbitmq
        - name: SERVER_PORT
          value: '8080'
  restartPolicy: Always

---
kind: Pod
apiVersion: v1
metadata:
  name: usage-logger
  labels:
    app: usage-cost-stream
spec:
  containers:
    - name: usage-logger
      image: hananiel/usagelogger:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: SPRING_RABBITMQ_ADDRESSES
          value: rabbitmq
        - name: SERVER_PORT
          value: '8080'
  restartPolicy: Always