kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortuneservice
  name: fortuneservice
  namespace: default
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: fortune-teller-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortune-teller-service
  name: fortune-teller-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-teller-service
  template:
    metadata:
      labels:
        app: fortune-teller-service
    spec:
      containers:
        - image: tscrypter/fortunetellerservicek8s:latest # TODO: update image repository
          name: fortune-teller-service
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            initialDelaySeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            initialDelaySeconds: 15
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortuneui
  name: fortuneui
  namespace: default
spec:
  ports:
    - name: http
      port: 80
  type: LoadBalancer
  selector:
    app: fortune-teller-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortune-teller-ui
  name: fortune-teller-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-teller-ui
  template:
    metadata:
      labels:
        app: fortune-teller-ui
    spec:
      containers:
        - image: tscrypter/fortunetelleruik8s:latest  # TODO: update image repository
          name: fortune-teller-ui
          env:
            - name: "spring__cloud__kubernetes__discovery__enabled"
              value: "true"
            - name: "spring__cloud__kubernetes__discovery__serviceName"
              value: "fortune-teller-ui"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            initialDelaySeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            initialDelaySeconds: 15
          ports:
            - containerPort: 80